import { useEffect, useState } from 'react'
import type { ReactNode } from 'react'
import { ArrowUpRight, Camera, Check, Clipboard, Code2, ExternalLink, GitBranch, Layers3, Mail, Menu, MessageCircle, Smartphone, Sparkles, X } from 'lucide-react'
import './App.css'
import { HeroScene } from './components/HeroScene'
import { profile } from './data/profile'
import { projects } from './data/projects'
import { ugcItems } from './data/ugc'
import { translations } from './i18n/translations'
import type { Language } from './i18n/translations'

const skills = { web: ['HTML/CSS', 'JavaScript'], code: ['Python', 'C++'], mobile: ['Flutter'], data: ['SQL'], design: ['Figma'] }

function App() {
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('portfolio-language') as Language) || 'kk')
  const [menuOpen, setMenuOpen] = useState(false)
  const [copied, setCopied] = useState<'copied' | 'failed' | null>(null)
  const [reducedMotion, setReducedMotion] = useState(false)
  const t = translations[language]
  useEffect(() => { localStorage.setItem('portfolio-language', language); document.documentElement.lang = language }, [language])
  useEffect(() => { const media = window.matchMedia('(prefers-reduced-motion: reduce)'); const update = () => setReducedMotion(media.matches); update(); media.addEventListener('change', update); return () => media.removeEventListener('change', update) }, [])
  const changeLanguage = (next: Language) => { setLanguage(next); setMenuOpen(false) }
  const copyEmail = async () => { try { await navigator.clipboard.writeText(profile.contacts.email); setCopied('copied') } catch { setCopied('failed') }; window.setTimeout(() => setCopied(null), 2200) }
  const mail = (subject: string) => `mailto:${profile.contacts.email}?subject=${encodeURIComponent(subject)}`
  return <div className="site-shell">
    <header className="site-header"><a className="brand" href="#top" aria-label="ayazbala home"><span className="brand-mark">a</span><span>{profile.brand}</span></a><nav className={`nav ${menuOpen ? 'is-open' : ''}`} aria-label="Main navigation">{Object.entries(t.nav).map(([id, label]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav><div className="header-actions"><div className="language-switcher" aria-label="Language">{(['kk', 'ru', 'en'] as Language[]).map(item => <button key={item} className={language === item ? 'active' : ''} onClick={() => changeLanguage(item)}>{item === 'kk' ? 'ҚАЗ' : item === 'ru' ? 'РУС' : 'ENG'}</button>)}</div><button className="menu-button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></header>
    <main id="top">
      <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" />{t.hero.eyebrow}</div><h1>{t.hero.title}</h1><p className="hero-lead">{t.hero.lead}</p><p className="hero-text">{t.hero.text}</p><div className="hero-actions"><a className="button button-primary" href="#contact">{t.hero.primary}<ArrowUpRight size={17} /></a><a className="button button-quiet" href="#projects">{t.hero.secondary}<span className="button-arrow">↓</span></a></div><div className="hero-bottom"><div className="social-row"><a href={profile.contacts.github} target="_blank" rel="noreferrer" aria-label="GitHub"><GitBranch size={18} /></a><a href={profile.contacts.instagram} target="_blank" rel="noreferrer" aria-label="Instagram"><Camera size={18} /></a><a href={profile.contacts.telegram} target="_blank" rel="noreferrer" aria-label="Telegram"><MessageCircle size={18} /></a></div><p className="availability"><span />{t.hero.availability}</p></div></div><HeroScene reducedMotion={reducedMotion} label={t.hero.sceneLabel} /></section>
      <section id="about" className="section about container"><div className="section-index">{t.about.kicker}</div><div className="about-grid"><div><h2>{t.about.title}</h2></div><div className="about-detail"><p className="body-large">{t.about.text}</p><div className="profile-meta"><div><span>{t.about.university}</span><strong>{t.about.study}</strong></div><div className="initials" aria-hidden="true">ҚА</div></div></div></div></section>
      <section id="skills" className="section skills-section"><div className="container"><div className="section-index">{t.skills.kicker}</div><div className="section-heading"><h2>{t.skills.title}</h2></div><div className="skills-grid">{Object.entries(skills).map(([key, items], index) => <div className="skill-group" key={key}><div className="skill-icon">{index === 0 ? <Code2 /> : index === 1 ? <Layers3 /> : index === 2 ? <Smartphone /> : index === 3 ? <Sparkles /> : <span>✦</span>}</div><h3>{t.skills[key as keyof typeof t.skills]}</h3><div className="skill-list">{items.map(item => <span key={item}>{item}</span>)}</div></div>)}</div></div></section>
      <section id="services" className="section container"><div className="section-index">{t.services.kicker}</div><div className="section-heading split"><h2>{t.services.title}</h2><p>{t.hero.text}</p></div><div className="services-grid"><ServiceCard number="01" icon={<Code2 />} title={t.services.webTitle} text={t.services.webText} /><ServiceCard number="02" icon={<Smartphone />} title={t.services.mobileTitle} text={t.services.mobileText} /><ServiceCard number="03" icon={<Sparkles />} title={t.services.ugcTitle} text={t.services.ugcText} /></div></section>
      <section id="projects" className="section projects-section"><div className="container"><div className="section-index">{t.projects.kicker}</div><div className="section-heading split"><h2>{t.projects.title}</h2><p>{t.projects.text}</p></div><div className="projects-grid">{projects.map((project, index) => <article className={`project-card ${project.accent}`} key={project.name}><div className="project-cover"><span>0{index + 1}</span><div className="cover-grid" /><strong>{project.name}</strong></div><div className="project-info"><h3>{project.name}</h3><p>{t.projects.empty}</p><span>{t.projects.link}</span></div></article>)}</div></div></section>
      <section id="ugc" className="section ugc-section container"><div className="section-index">{t.ugc.kicker}</div><div className="ugc-layout"><div><h2>{t.ugc.title}</h2><p className="body-large">{t.ugc.text}</p></div><div className="ugc-empty"><div className="empty-icon"><Sparkles size={20} /></div><p>{ugcItems.length ? ugcItems[0].title : t.ugc.empty}</p><div className="ugc-links"><a href={profile.contacts.instagram} target="_blank" rel="noreferrer">{t.ugc.instagram}<ExternalLink size={14} /></a><a href={profile.contacts.tiktok} target="_blank" rel="noreferrer">{t.ugc.tiktok}<ExternalLink size={14} /></a></div></div></div></section>
      <section id="contact" className="section contact-section"><div className="container"><div className="section-index">{t.contact.kicker}</div><div className="contact-layout"><div><h2>{t.contact.title}</h2><p className="body-large">{t.contact.text}</p><div className="contact-main"><a className="email-link" href={`mailto:${profile.contacts.email}`}>{profile.contacts.email}<ArrowUpRight size={18} /></a><button className="copy-button" onClick={copyEmail}>{copied === 'copied' ? <Check size={15} /> : copied === 'failed' ? <X size={15} /> : <Clipboard size={15} />}{copied === 'copied' ? t.contact.copied : copied === 'failed' ? t.contact.copyFailed : t.contact.copy}</button></div></div><div className="contact-options"><ContactLink href={mail(t.contact.work)} icon={<Mail size={19} />} label={t.contact.work} /><ContactLink href={mail(t.contact.website)} icon={<Code2 />} label={t.contact.website} /><ContactLink href={mail(t.contact.collab)} icon={<Sparkles />} label={t.contact.collab} /></div></div><div className="contact-footer"><a href={`tel:${profile.contacts.phone.replaceAll(' ', '')}`}>{t.contact.phone}: <strong>{profile.contacts.phone}</strong></a><div className="contact-socials"><a href={profile.contacts.github} target="_blank" rel="noreferrer"><GitBranch size={17} /></a><a href={profile.contacts.telegram} target="_blank" rel="noreferrer"><MessageCircle size={17} /></a><a href={profile.contacts.whatsapp} target="_blank" rel="noreferrer"><Smartphone size={17} /></a></div></div></div></section>
    </main><footer className="site-footer container"><span>© {profile.brand}</span><span>{t.footer.note}</span><a href="#top">{t.footer.top} <ArrowUpRight size={14} /></a></footer>
  </div>
}
function ServiceCard({ number, icon, title, text }: { number: string; icon: ReactNode; title: string; text: string }) { return <article className="service-card"><div className="service-top"><span>{number}</span><div className="service-icon">{icon}</div></div><h3>{title}</h3><p>{text}</p></article> }
function ContactLink({ href, icon, label }: { href: string; icon: ReactNode; label: string }) { return <a className="contact-option" href={href}><span>{icon}</span>{label}<ArrowUpRight size={16} /></a> }
export default App
